"""add consent sync and accrual tables

Revision ID: 0e44aefbf8b3
Revises: 001
Create Date: 2026-03-05 19:31:25.144804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e44aefbf8b3"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bonus_accrual_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_bonus_accrual_idempotency_key"),
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("list_id", sa.BigInteger(), nullable=False),
        sa.Column("watermark_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watermark_subscriber_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "list_id", name="uq_sync_state_source_list"),
    )
    op.add_column(
        "listmonk_users",
        sa.Column("consent_pending", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "listmonk_users",
        sa.Column("consent_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "listmonk_users",
        sa.Column("consent_confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column("listmonk_users", "consent_pending", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listmonk_users", "consent_confirmed_at")
    op.drop_column("listmonk_users", "consent_checked_at")
    op.drop_column("listmonk_users", "consent_pending")
    op.drop_table("sync_state")
    op.drop_table("bonus_accrual_log")
    # ### end Alembic commands ###
