"""add consent sync and accrual tables

Revision ID: 0e44aefbf8b3
Revises: 001
Create Date: 2026-03-05 19:31:25.144804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e44aefbf8b3'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Create new database structures for bonus accruals and synchronization, and add consent fields to listmonk_users.
    
    Creates the table `bonus_accrual_log` (with id, user_id, reason, idempotency_key, status, payload, error_text, created_at, updated_at, processed_at and a unique constraint on idempotency_key), creates the table `sync_state` (with id, source, list_id, watermark_updated_at, watermark_subscriber_id, updated_at and a unique constraint on (source, list_id)), and adds the columns `consent_pending`, `consent_checked_at`, and `consent_confirmed_at` to `listmonk_users`, then removes the server default from `consent_pending`.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_accrual_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_bonus_accrual_idempotency_key')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('list_id', sa.BigInteger(), nullable=False),
    sa.Column('watermark_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watermark_subscriber_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'list_id', name='uq_sync_state_source_list')
    )
    op.add_column(
        'listmonk_users',
        sa.Column('consent_pending', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('listmonk_users', sa.Column('consent_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listmonk_users', sa.Column('consent_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('listmonk_users', 'consent_pending', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes introduced by the migration by removing consent-related columns and dropping the newly added tables.
    
    Drops 'consent_confirmed_at', 'consent_checked_at', and 'consent_pending' from the 'listmonk_users' table, then drops the 'sync_state' and 'bonus_accrual_log' tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listmonk_users', 'consent_confirmed_at')
    op.drop_column('listmonk_users', 'consent_checked_at')
    op.drop_column('listmonk_users', 'consent_pending')
    op.drop_table('sync_state')
    op.drop_table('bonus_accrual_log')
    # ### end Alembic commands ###
