"""add referal and tags to users

Revision ID: 1620d633d874
Revises: e2c76c887215
Create Date: 2026-03-17 02:18:18.849026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1620d633d874'
down_revision: Union[str, Sequence[str], None] = 'e2c76c887215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referal', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tags')
    op.drop_column('users', 'referal')
    # ### end Alembic commands ###
