"""add listmonk subscriber unique constraint

Revision ID: 34a51aad1253
Revises: 693febcf3f05
Create Date: 2026-03-18 09:21:03.761127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a51aad1253'
down_revision: Union[str, Sequence[str], None] = '693febcf3f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_listmonk_users_subscriber_id', 'listmonk_users', ['subscriber_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_listmonk_users_subscriber_id', 'listmonk_users', type_='unique')
    # ### end Alembic commands ###
