"""add listmonk subscriber archive

Revision ID: 693febcf3f05
Revises: 8d37d7408984
Create Date: 2026-03-18 07:46:22.692250

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "693febcf3f05"
down_revision: str | Sequence[str] | None = "8d37d7408984"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listmonk_user_archive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subscriber_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("list_ids", sa.String(length=255), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("consent_pending", sa.Boolean(), nullable=False),
        sa.Column("consent_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_reason", sa.String(length=64), nullable=False),
        sa.Column("winner_user_id", sa.BigInteger(), nullable=True),
        sa.Column("winner_subscriber_id", sa.BigInteger(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listmonk_user_archive_subscriber_id"),
        "listmonk_user_archive",
        ["subscriber_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listmonk_user_archive_user_id"), "listmonk_user_archive", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_listmonk_user_archive_winner_user_id"),
        "listmonk_user_archive",
        ["winner_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_listmonk_user_archive_winner_user_id"), table_name="listmonk_user_archive"
    )
    op.drop_index(op.f("ix_listmonk_user_archive_user_id"), table_name="listmonk_user_archive")
    op.drop_index(
        op.f("ix_listmonk_user_archive_subscriber_id"), table_name="listmonk_user_archive"
    )
    op.drop_table("listmonk_user_archive")
    # ### end Alembic commands ###
