"""add external call outbox

Revision ID: 9bac67d00026
Revises: 34a51aad1253
Create Date: 2026-03-30 13:17:41.901197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9bac67d00026"
down_revision: str | Sequence[str] | None = "34a51aad1253"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_call_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("source_event_id", sa.String(length=64), nullable=True),
        sa.Column("queue_name", sa.String(length=64), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_external_call_outbox_dedupe_key"),
    )
    op.create_index(
        op.f("ix_external_call_outbox_operation"),
        "external_call_outbox",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_call_outbox_status"),
        "external_call_outbox",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_call_outbox_user_id"),
        "external_call_outbox",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_external_call_outbox_user_id"), table_name="external_call_outbox")
    op.drop_index(op.f("ix_external_call_outbox_status"), table_name="external_call_outbox")
    op.drop_index(op.f("ix_external_call_outbox_operation"), table_name="external_call_outbox")
    op.drop_table("external_call_outbox")
    # ### end Alembic commands ###
