"""RabbitMQ queue names. Use only these constants, never raw strings."""

QUEUE_CREATE = "queue-create"
QUEUE_UPDATE = "queue-update"
QUEUE_DELETE = "queue-delete"
QUEUE_MERGE = "queue-request-to-merge"
QUEUE_CREATE_RETRY = f"{QUEUE_CREATE}-retry"
QUEUE_UPDATE_RETRY = f"{QUEUE_UPDATE}-retry"
QUEUE_DELETE_RETRY = f"{QUEUE_DELETE}-retry"
QUEUE_CREATE_DEAD = f"{QUEUE_CREATE}-dead"
QUEUE_UPDATE_DEAD = f"{QUEUE_UPDATE}-dead"
QUEUE_DELETE_DEAD = f"{QUEUE_DELETE}-dead"
